package gui;

import dtn.Network;
import java.awt.Graphics2D;

public class SimulationGUI extends javax.swing.JFrame {

    /** Creates new form SimulationGUI */
    public SimulationGUI() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        simulationPanel = new SimulationPanel();
        setBackground(new java.awt.Color(255, 255, 255));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout SimulationPanelLayout = new javax.swing.GroupLayout(simulationPanel);
        simulationPanel.setLayout(SimulationPanelLayout);
        SimulationPanelLayout.setHorizontalGroup(
                SimulationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 550, Short.MAX_VALUE));
        SimulationPanelLayout.setVerticalGroup(
                SimulationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 550, Short.MAX_VALUE));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(simulationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(simulationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

        pack();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new SimulationGUI().setVisible(true);
            }
        });
    }

    public void paint(Graphics2D g) throws InterruptedException {
        simulationPanel.repaint();
        simulationPanel.revalidate();
    }

    public void setNetwork(Network n) {
        simulationPanel.setNetwork(n);
    }
    // Variables declaration - do not modify
    public SimulationPanel simulationPanel;
    // End of variables declaration
}
