/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SimulationPanel.java
 *
 * Created on Dec 12, 2010, 11:24:54 PM
 */

package gui;

import dtn.Network;
import dtn.Node;
import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author Renegade
 */
public class SimulationPanel extends javax.swing.JPanel {

    /** Creates new form SimulationPanel */
    public SimulationPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 477, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

     public void paint(Graphics g) {
        // Dynamically calculate size information
        if (network != null) {
            for (Node n : network.agentList) {

                switch (n.state) {
                    case 'S': g.setColor(Color.green); break;
                    case 'I': g.setColor(Color.red); break;
                    case 'R': g.setColor(Color.blue); break;
                }
                g.fillOval((int) (5*n.posX), (int) (5*n.posY), 3, 3);
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

     public void setNetwork ( Network network ) {
         this.network = network;
     }

     private Network network;
}
